[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["package.json"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
